CREATE DATABASE sr_test;
CREATE USER sr_amaro WITH PASSWORD '5r_4m4r0';

\connect sr_test

CREATE SCHEMA IF NOT EXISTS sr_amaro AUTHORIZATION sr_amaro;
GRANT CREATE ON DATABASE sr_test to sr_amaro;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA sr_amaro TO sr_amaro;
GRANT USAGE ON SCHEMA sr_amaro TO sr_amaro;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA sr_amaro TO sr_amaro;
GRANT SELECT, INSERT, UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA sr_amaro  TO sr_amaro;
ALTER DATABASE sr_test OWNER TO sr_amaro;
CREATE EXTENSION postgis;